version: '3'
services:
    mongodb:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        expose:
            - "27017"
        networks:
            - app_backend
        volumes:
            - /data_db:/data/db
            - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    backend:
        build: .
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        expose:
            - "3000"
            - "2000"
        ports:
            - 3000:3000
            - 2000:2000
        command: npm run start
        networks:
            - app_backend
        depends_on:
            - mongodb
    frontend:
        build: ./client
        volumes:
            - ./client:/usr/app/client/
            - /usr/app/client/node_modules
        expose:
            - "4200"
        ports:
            - 4200:4200
        command: npm run start
        networks:
            - app_backend
        links:
            - backend
        depends_on:
            - backend
networks:
    app_backend:

