version: '3'
services:
    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 123
            MONGO_INITDB_DATABASE: dental
        ports:
            - 27017:27017
        expose:
            - "27017"
        networks:
            - app_backend
        volumes:
            - /data_db:/data/db
    backend:
        build: .
        volumes:
            - .:/usr/app/
            - /usr/app/node_modules
        expose:
            - "3000"
        ports:
            - 3000:3000
        command: npm run start
        networks:
            - app_backend
        depends_on:
            - mongodb
    frontend:
        build:
            context: ./client
        volumes:
            - /client:/usr/app/client/
            - /usr/app/client/node_modules
        expose:
            - "4200"
        ports:
            - 4200:4200
        command: ng serve
        networks:
            - app_backend
        depends_on:
            - backend
networks:
    app_backend:

